#ifndef MBEDTLS_CONFIG_H
#define MBEDTLS_CONFIG_H

/* Align with Pico W TLS example expectations for mbedTLS + lwIP altcp_tls */
#include <limits.h>

#ifndef MBEDTLS_ALLOW_PRIVATE_ACCESS
#define MBEDTLS_ALLOW_PRIVATE_ACCESS
#endif

#ifndef MBEDTLS_NO_PLATFORM_ENTROPY
#define MBEDTLS_NO_PLATFORM_ENTROPY
#endif

#ifndef MBEDTLS_ENTROPY_HARDWARE_ALT
#define MBEDTLS_ENTROPY_HARDWARE_ALT
#endif

#ifndef MBEDTLS_HAVE_TIME
#define MBEDTLS_HAVE_TIME
#endif

#ifndef MBEDTLS_PLATFORM_MS_TIME_ALT
#define MBEDTLS_PLATFORM_MS_TIME_ALT
#endif

#include "mbedtls/mbedtls_config.h"

#ifdef MBEDTLS_TIMING_C
#undef MBEDTLS_TIMING_C
#endif

#ifdef MBEDTLS_NET_C
#undef MBEDTLS_NET_C
#endif

#ifdef MBEDTLS_FS_IO
#undef MBEDTLS_FS_IO
#endif

#ifdef MBEDTLS_PSA_ITS_FILE_C
#undef MBEDTLS_PSA_ITS_FILE_C
#endif

#ifdef MBEDTLS_PSA_CRYPTO_STORAGE_C
#undef MBEDTLS_PSA_CRYPTO_STORAGE_C
#endif

#ifdef MBEDTLS_PSA_CRYPTO_C
#undef MBEDTLS_PSA_CRYPTO_C
#endif

#ifdef MBEDTLS_USE_PSA_CRYPTO
#undef MBEDTLS_USE_PSA_CRYPTO
#endif

#ifdef MBEDTLS_SHA3_C
#undef MBEDTLS_SHA3_C
#endif

#ifdef MBEDTLS_LMS_C
#undef MBEDTLS_LMS_C
#endif

#ifdef MBEDTLS_SSL_PROTO_TLS1_3
#undef MBEDTLS_SSL_PROTO_TLS1_3
#endif

#ifdef MBEDTLS_SSL_TLS1_3_KEY_EXCHANGE_MODE_EPHEMERAL_ENABLED
#undef MBEDTLS_SSL_TLS1_3_KEY_EXCHANGE_MODE_EPHEMERAL_ENABLED
#endif

#ifdef MBEDTLS_SSL_TLS1_3_KEY_EXCHANGE_MODE_PSK_EPHEMERAL_ENABLED
#undef MBEDTLS_SSL_TLS1_3_KEY_EXCHANGE_MODE_PSK_EPHEMERAL_ENABLED
#endif

#ifdef MBEDTLS_SSL_TLS1_3_COMPATIBILITY_MODE
#undef MBEDTLS_SSL_TLS1_3_COMPATIBILITY_MODE
#endif

#ifdef MBEDTLS_SSL_TLS1_3_TICKET_AGE_TOLERANCE
#undef MBEDTLS_SSL_TLS1_3_TICKET_AGE_TOLERANCE
#endif

#ifdef MBEDTLS_SSL_TLS1_3_TICKET_NONCE_LENGTH
#undef MBEDTLS_SSL_TLS1_3_TICKET_NONCE_LENGTH
#endif

#endif