// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXb-OJCh5jRUcD-lCj-P6W1_071Z40F8g',
    appId: '1:208763793413:web:e5a46c294ff74364232c6c',
    messagingSenderId: '208763793413',
    projectId: 'projeto-final-5eb42',
    authDomain: 'projeto-final-5eb42.firebaseapp.com',
    databaseURL: 'https://projeto-final-5eb42-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-final-5eb42.firebasestorage.app',
    measurementId: 'G-5ZECH3L3VM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqhDKkonZZYWH7kZf0YYkw0WI9-PfiKkI',
    appId: '1:208763793413:android:e459ae67966ea7d1232c6c',
    messagingSenderId: '208763793413',
    projectId: 'projeto-final-5eb42',
    databaseURL: 'https://projeto-final-5eb42-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-final-5eb42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB53oguBkgslYmpOLveuZjkr3DMEaz4Ijc',
    appId: '1:208763793413:ios:04becfe6b1dc1042232c6c',
    messagingSenderId: '208763793413',
    projectId: 'projeto-final-5eb42',
    databaseURL: 'https://projeto-final-5eb42-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-final-5eb42.firebasestorage.app',
    iosBundleId: 'com.example.projetoFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB53oguBkgslYmpOLveuZjkr3DMEaz4Ijc',
    appId: '1:208763793413:ios:04becfe6b1dc1042232c6c',
    messagingSenderId: '208763793413',
    projectId: 'projeto-final-5eb42',
    databaseURL: 'https://projeto-final-5eb42-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-final-5eb42.firebasestorage.app',
    iosBundleId: 'com.example.projetoFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXb-OJCh5jRUcD-lCj-P6W1_071Z40F8g',
    appId: '1:208763793413:web:db0169f4d1610ad5232c6c',
    messagingSenderId: '208763793413',
    projectId: 'projeto-final-5eb42',
    authDomain: 'projeto-final-5eb42.firebaseapp.com',
    databaseURL: 'https://projeto-final-5eb42-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-final-5eb42.firebasestorage.app',
    measurementId: 'G-T9Z2KBWWMZ',
  );
}
